<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SeanTool.CSharp.FileTool" Version="0.0.3" />
    <PackageReference Include="SeanTool.CSharp.JsonTool" Version="0.0.4" />
    <PackageReference Include="SeanTool.CSharp.XMLTool" Version="0.0.3" />
    <PackageReference Include="SeanTool.CSharp.ZipTool" Version="0.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ErrorHelper.Core\ErrorHelper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\AppSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="Config\IISLogFolderList.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="Config\ElmahFolderList.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
    <None Update="Config\LogFolderList.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </None>
  </ItemGroup>

</Project>
