name: Publish .NET App

on:
  push:
    tags:
      - 'v*.*.*'   # 例如推送 v1.0.0 時觸發

permissions:
  contents: write  # 讓 GITHUB_TOKEN 能建立 Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get version from tag
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore dependencies
        run: dotnet restore ./DotNet/ErrorHelper.App/ErrorHelper.App.csproj

      - name: Publish (single file, self-contained, win-x64)
        run: >
          dotnet publish ./DotNet/ErrorHelper.App/ErrorHelper.App.csproj
          -c Release
          -r win-x64
          -p:PublishSingleFile=true
          -p:SelfContained=true
          -p:Version=${{ steps.version.outputs.version }}
          -o ./DotNet/ErrorHelper.App/Release/build

      - name: Archive build
        run: |
          mkdir -p artifacts
          Compress-Archive -Path "./DotNet/ErrorHelper.App/Release/build/*" -DestinationPath "artifacts/ErrorHelper.App-${{ steps.version.outputs.version }}.zip"
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: artifacts/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}